strings:
  welcome: "Привет! Давайте начнем."
  height: "Введите ваш рост в см:"
  weight: "Введите ваш вес в кг:"
  age: "Введите ваш возраст в годах:"
  gender: "Укажите ваш пол:"
  activity_level: "Введите вашу обычную физическую активность:"
  goal: "Выберите вашу цель:"
  confirmation: "Спасибо за предоставленную информацию! Ваша информация была сохранена."
  process_image: "Пожалуйста, отправьте фотографию вашего блюда."
  no_data: "Для вас нет данных. Пожалуйста, введите информацию о себе через меню."
  enter_meal: "Введите информацию о приеме пищи."
  enter_calories: "Введите количество килокалорий."
  enter_carbs: "Введите количество углеводов в граммах."
  enter_proteins: "Введите количество белка в граммах."
  enter_fats: "Введите количество жиров в граммах."
  enter_comment: "Введите комментарий, например, список ингредиентов."
menu:
  gender:
    male:
        id: "0"
        string: "Женский"
    female:
        id: "1"
        string: "Мужской"
  activity_level:
    sedentary:
      id: "0"
      string: "Сидячий образ жизни"
    low:
      id: "1"
      string: "Низкая активность"
    moderate:
      id: "2"
      string: "Средняя активность"
    high:
      id: "3"
      string: "Высокая активность"
  goal:
    gain:
      id: "0"
      string: "Набрать вес"
    lose:
      id: "1"
      string: "Снизить вес"
    maintain:
      id: "2"
      string: "Удержать вес"
